import type { NextPage } from "next";
import Head from "next/head";
import HomePage from "./Home";
import styles from "../../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className="bg-bl-900 h-screen font-normal font-sans">
      <div className={styles.container}>
        <Head>
          <title>Meu Portifólio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <HomePage />
      </div>
    </div>
  );
};

export default Home;
