import type { NextPage } from "next";
import Head from "next/head";
import HomePage from "./Home";

const Home: NextPage = () => {
  return (
    <div className="bg-bl-900 mx-auto max-w-[90rem] px-4">
      <div>
        <Head>
          <title>Meu Portifólio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <HomePage />
      </div>
    </div>
  );
};

export default Home;
